# name: portfolio
# description: A new Flutter project.

# # The following line prevents the package from being accidentally published to
# # pub.dev using `flutter pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# # The following defines the version and build number for your application.
# # A version number is three numbers separated by dots, like 1.2.43
# # followed by an optional build number separated by a +.
# # Both the version and the builder number may be overridden in flutter
# # build by specifying --build-name and --build-number, respectively.
# # In Android, build-name is used as versionName while build-number used as versionCode.
# # Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# # In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# # Read more about iOS versioning at
# # https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# # In Windows, build-name is used as the major, minor, and patch parts
# # of the product and file versions while build-number is used as the build suffix.
# version: 1.0.0+1

# environment:
#   sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
#     web_view flutter
  
#   #*Icon
#   cupertino_icons: ^1.0.3
#   # flutter_icons:
#   #   git:
#   #     url: https://github.com/flutter-studio/flutter-icons.git
# #   flutter_icons:
# # #    path: ../
# #      git:
# #        url: https://github.com/flutter-studio/flutter-icons.git
# #        ref: 1.1.0
#   font_awesome_flutter: ^9.1.0

#   #*Architecture
#   stacked: ^2.2.7
#   stacked_services: ^0.8.15
#   responsive_builder: ^0.4.1
#   get_it: ^7.2.0
#   injectable: ^1.5.0
#   flutter_hooks: ^0.18.0
#   url_strategy: ^0.2.0

#   #*Services
#   url_launcher: ^6.0.12
#   http: ^0.13.4

#   #*Utilities
#   collapsible_sidebar: ^2.0.1+2
#   animated_text_kit: ^4.2.1
#   simple_animations: ^4.0.1
#   oktoast: ^3.1.3+1
#   flutter_neumorphic:
#     git:
#       url: git://github.com/tsvillain/Flutter-Neumorphic.git

#   animations: ^2.0.1
#   carousel_slider: ^4.0.0
#   flutter_neumorphic: ^3.2.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

#   # flutter_launcher_icons: ^0.11.0   

#   # flutter_icons:
#   # includes:
#   #   - ant

#   flutter_lints: ^2.0.0
#   injectable_generator: ^1.5.2
#   auto_route_generator: ^2.4.1
#   build_runner: ^2.1.4
#   change_app_package_name: ^1.0.0
# flutter:
#   uses-material-design: true
#   assets:
#     - assets/images/
#   fonts:
#     - family: Lora
#       fonts:
#         - asset: assets/fonts/Lora.ttf
#     - family: Montserrat
#       fonts:
#         - asset: assets/fonts/Montserrat.ttf

name: portfolio
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  #*Icons
  cupertino_icons: ^1.0.3
  flutter_icons:
    git:
      url: https://github.com/flutter-studio/flutter-icons.git
  font_awesome_flutter: ^9.1.0

  #*Architecture
  stacked: ^2.2.7
  stacked_services: ^0.8.15
  responsive_builder: ^0.4.1
  get_it: ^7.2.0
  injectable: ^1.5.0
  flutter_hooks: ^0.18.0
  url_strategy: ^0.2.0

  #*Services
  url_launcher: ^6.0.12
  http: ^0.13.4

  #*Utilities
  collapsible_sidebar: ^2.0.1+2
  animated_text_kit: ^4.2.1
  simple_animations: ^4.0.1
  oktoast: ^3.1.3+1
  flutter_neumorphic: ^3.2.0


  animations: ^2.0.1
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  injectable_generator: ^1.5.2
  auto_route_generator: ^2.4.1
  build_runner: ^2.1.4
  change_app_package_name: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
